export { FontExporter } from '@font-exporter';
export type { IFontExporterJsonEntry, IFontExporterOptions } from '@font-exporter';
export { IconFontLibrary } from '@main';
export type { IIconFontLibraryOptions, IIconFontLibraryResult, IUnicodeAssignment, TUnicodeAssignmentStrategy } from '@main';
export { SvgLoader } from '@svg-loader';
export type { ISvgLoaderOptions, ISvgLoaderResult } from '@svg-loader';
export { SvgParser } from '@svg-parser';
export type { ISvgParserResult, ISvgShape, ISvgViewBox, TStandardFigure } from '@svg-parser';
export { SvgNormalizer } from '@svg-normalizer';
export type { ISvgNormalizerOptions, ISvgNormalizerResult } from '@svg-normalizer';
export { SvgWindingCorrector } from '@svg-winding-corrector';
export type { IPoint2D } from '@svg-winding-corrector';
export { SvgOpentypeTransformer } from '@svg-opentype-transformer';
export type { IFontOptions, IGlyphDefinition } from '@svg-opentype-transformer';
export { unplugin } from './plugins';
export type { UnpluginIconFontOptions } from './plugins';
